alter session set "_ORACLE_SCRIPT"=true;
 
CREATE USER NBA
IDENTIFIED by NBA
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA 20M ON USERS;

GRANT "CONNECT" TO NBA;
GRANT "RESOURCE" TO NBA;

GRANT ALTER ANY INDEX TO NBA;
GRANT ALTER ANY SEQUENCE TO NBA;
GRANT ALTER ANY TABLE TO NBA;
GRANT ALTER ANY TRIGGER TO NBA;
GRANT CREATE ANY INDEX TO NBA;
GRANT CREATE ANY SEQUENCE TO NBA;
GRANT CREATE ANY SYNONYM TO NBA;
GRANT CREATE ANY TABLE TO NBA;
GRANT CREATE ANY TRIGGER TO NBA;
GRANT CREATE ANY VIEW TO NBA;
GRANT CREATE PROCEDURE TO NBA;
GRANT CREATE PUBLIC SYNONYM TO NBA;
GRANT CREATE TRIGGER TO NBA;
GRANT CREATE VIEW TO NBA;
GRANT DELETE ANY TABLE TO NBA;
GRANT DROP ANY INDEX TO NBA;
GRANT DROP ANY SEQUENCE TO NBA;
GRANT DROP ANY TABLE TO NBA;


